[package]
name = "stemmgpt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] } # for command-line parsing
crossterm = "0.27" # for terminal control and animations
rand = "0.8" # for random elements